### ISSUE TITLE
Sizes convention update 

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#225]
Sizes should be updated to match the image below, the EU convention currently in use should be replaced with the international one as follows:
Women's: (extra)Small, Medium, (extra)Large
Men's: (extra)Small, Medium, (extra)Large
Kid's: should remain the same

<img width="230" alt="Screenshot 2022-04-26 at 09 56 26" src="https://user-images.githubusercontent.com/52887737/166507859-255ec652-46e2-40f2-bef9-6ac7c77bbbf3.png">

**Comment by tberm** [comment]
Do we just want to update the size categories in the frontend or also convert the sizes selected for existing loops in Firebase to the new options? Obviously the latter is a bit more tricky, but since currently there are just six loops that have been created I guess we could just go through and update the sizes by hand...

**Comment by giuliamml** [comment]
> Refe
Don't worry about updating the existing ones on Firebase, just the front end part is enough. I'll communicate the change to the loop hosts, so they can update according to what works for them!
