### ISSUE TITLE
add data conset checkbox to form

### ISSUE THREAD

**Issue by giuliamml** [CollActionteam/clothing-loop#81]
At the bottom of each signup form, before the submit button, add a *required* checkbox for user data consent (at a later stage, we'll add a link to a 'how we use your data' page/popup

Actions for the checkbox:
- The form should be submitted only if the user ticks the checkbox, alternatively display an error msg
- The checkbox value should be added to Firebase

Forms are displayed in the following pages:
- NewChainSignup.tsx
- Signup.tsx

**Comment by kfless12** [comment]
Updated the UI to include the checkbox with an error message if the user doesnt check it. I added the necessary changes to the firebase end of the app but I am not sure how to test the upload as it seems like the function needs to be pushed up with changes to the git repo in order to update the firebase "createUser" fuinction. Ill put in a pull request for the changes for now.
